# Generated by Django 2.1 on 2019-04-25 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_address', models.CharField(max_length=10)),
                ('amount_sent', models.DecimalField(decimal_places=3, max_digits=3)),
                ('network', models.CharField(default='MTN', max_length=15)),
                ('Number', models.IntegerField(default='+233XXXXXXXXX')),
                ('location', models.CharField(default='GARU', max_length=25)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Transaction_Details', models.TextField()),
                ('Accepted', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='Pending', max_length=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
