# Generated by Django 2.1 on 2019-02-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rooms_count', models.IntegerField()),
                ('parking_space', models.IntegerField()),
                ('shower', models.IntegerField()),
                ('banner', models.ImageField(blank=True, default=None, null=True, upload_to='hotels')),
            ],
        ),
    ]
