# Generated by Django 2.1 on 2019-05-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rooms_count', models.IntegerField()),
                ('parking_space', models.IntegerField()),
                ('shower', models.IntegerField()),
                ('banner', models.ImageField(blank=True, default=None, null=True, upload_to='hotels')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('second_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='realtors/%Y/%m/%d/')),
                ('telephone', models.IntegerField(blank=True, default=None, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('website', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('about', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Realtor'),
        ),
    ]
