# Generated by Django 2.1 on 2020-08-14 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20200813_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Realtor',
            new_name='Manager',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='realtor',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='parking_space',
            new_name='parking',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='shower',
            new_name='rate',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='rooms_count',
            new_name='rooms',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='banner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Photo'),
        ),
    ]
