# Generated by Django 2.1 on 2020-10-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200813_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
