# Generated by Django 2.1 on 2019-02-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='houses/%Y/%m/%d')),
                ('description', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
