# Generated by Django 2.1 on 2019-02-20 01:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='category',
            field=models.CharField(blank=True, default='All', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='houses/%Y/%m/%d/'),
        ),
    ]
