# Generated by Django 2.1 on 2019-03-26 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('about',)},
        ),
        migrations.RenameField(
            model_name='house',
            old_name='name',
            new_name='about',
        ),
    ]
