# Generated by Django 2.1 on 2020-07-15 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190727_0735'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Town', 'verbose_name_plural': 'Towns'},
        ),
    ]
