# Generated by Django 2.1 on 2020-08-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='artisans/%Y/%m/%d/'),
        ),
    ]
