# Generated by Django 2.1 on 2020-08-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisans', '0003_auto_20200813_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisan',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='artisans/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
